import type { TaskSeed } from '../pilot/tasks.ts';

/** 12 real-ish tasks: multi-file, varied bug classes, regression traps. */
export const VALID_SEEDS: TaskSeed[] = [
  {
    id: 'v-discount', file: 'price.py',
    buggy: 'def total(items):\n    return sum(i["price"] for i in items)\n',
    frozenName: 'test_t0.py',
    frozenSrc: 'from price import total\ndef test_disc(): assert total([{"price": 100, "qty": 2}]) == 200\ndef test_multi(): assert total([{"price": 10, "qty": 1}, {"price": 5, "qty": 3}]) == 25\ndef test_empty(): assert total([]) == 0\n',
    devName: 'test_dev.py',
    devSrc: 'from price import total\ndef test_smoke(): assert total([{"price": 10, "qty": 1}]) == 10\n',
    brief: 'total(items) must multiply price*qty per item, currently ignores qty.',
  },
  {
    id: 'v-sort', file: 'rank.py',
    buggy: 'def top(ps):\n    return sorted(ps, key=lambda p: p["name"])[:3]\n',
    frozenName: 'test_t0.py',
    frozenSrc: 'from rank import top\nPS=[{"name":"b","score":5},{"name":"a","score":9},{"name":"c","score":7},{"name":"d","score":1}]\ndef test_order(): assert [p["name"] for p in top(PS)] == ["a","c","b"]\ndef test_few(): assert [p["name"] for p in top(PS[:2])] == ["a","b"]\n',
    devName: 'test_dev.py',
    devSrc: 'from rank import top\ndef test_smoke(): assert len(top([{"name":"x","score":1}])) == 1\n',
    brief: 'top(ps) must return top-3 by score descending, currently sorts by name.',
  },
  {
    id: 'v-dedup', file: 'dedup.py',
    buggy: 'def dedup(xs):\n    return list(set(xs))\n',
    frozenName: 'test_t0.py',
    frozenSrc: 'from dedup import dedup\ndef test_order(): assert dedup([3,1,2,1,3]) == [3,1,2]\ndef test_empty(): assert dedup([]) == []\ndef test_str(): assert dedup(["b","a","b"]) == ["b","a"]\n',
    devName: 'test_dev.py',
    devSrc: 'from dedup import dedup\ndef test_smoke(): assert sorted(dedup([1,1,2])) == [1,2]\n',
    brief: 'dedup(xs) must remove duplicates preserving first-seen order, currently scrambles order via set.',
  },
  {
    id: 'v-retry', file: 'retry.py',
    buggy: 'def attempts(n):\n    return list(range(1, n))\n',
    frozenName: 'test_t0.py',
    frozenSrc: 'from retry import attempts\ndef test_three(): assert attempts(3) == [1,2,3]\ndef test_one(): assert attempts(1) == [1]\n',
    devName: 'test_dev.py',
    devSrc: 'from retry import attempts\ndef test_smoke(): assert attempts(2) == [1,2]\n',
    brief: 'attempts(n) must yield attempt numbers 1..n inclusive for n retries, currently one short.',
  },
  {
    id: 'v-pct', file: 'pct.py',
    buggy: 'def pct(a, b):\n    return a // b * 100\n',
    frozenName: 'test_t0.py',
    frozenSrc: 'from pct import pct\ndef test_half(): assert pct(1, 2) == 50\ndef test_third(): assert pct(1, 3) == 33\ndef test_full(): assert pct(5, 5) == 100\n',
    devName: 'test_dev.py',
    devSrc: 'from pct import pct\ndef test_smoke(): assert pct(2, 2) == 100\n',
    brief: 'pct(a,b) must return integer percent a/b, currently floor-divides before multiplying.',
  },
  {
    id: 'v-csv', file: 'csvsum.py',
    buggy: 'def colsum(path, col):\n    import csv\n    total = 0\n    with open(path) as f:\n        rows = list(csv.reader(f))\n    for r in rows[2:]:\n        total += int(r[col])\n    return total\n',
    frozenName: 'test_t0.py',
    frozenSrc: 'from csvsum import colsum\ndef test_sum(tmp_path):\n    p = tmp_path / "d.csv"\n    p.write_text("h1,h2\\n5,7\\n3,4\\n")\n    assert colsum(str(p), 0) == 8\n    assert colsum(str(p), 1) == 11\n',
    devName: 'test_dev.py',
    devSrc: 'from csvsum import colsum\ndef test_smoke(tmp_path):\n    p = tmp_path / "d.csv"\n    p.write_text("h\\n9\\n")\n    assert colsum(str(p), 0) == 9\n',
    brief: 'colsum must skip exactly the header row, currently skips header plus first data row.',
  },
  {
    id: 'v-get', file: 'cfg.py',
    buggy: 'def timeout(cfg):\n    return cfg["timeout"]\n',
    frozenName: 'test_t0.py',
    frozenSrc: 'from cfg import timeout\ndef test_set(): assert timeout({"timeout": 5}) == 5\ndef test_missing(): assert timeout({}) == 30\ndef test_none(): assert timeout({"timeout": None}) == 30\n',
    devName: 'test_dev.py',
    devSrc: 'from cfg import timeout\ndef test_smoke(): assert timeout({"timeout": 5}) == 5\n',
    brief: 'timeout(cfg) must return cfg timeout or default 30 when missing/None, currently raises/returns None.',
  },
  {
    id: 'v-jsondt', file: 'jenc.py',
    buggy: 'import json\ndef dump(o):\n    return json.dumps(o)\n',
    frozenName: 'test_t0.py',
    frozenSrc: 'import json\nfrom datetime import datetime\nfrom jenc import dump\ndef test_dt(): assert json.loads(dump({"t": datetime(2024,1,2,3,4,5)})) == {"t": "2024-01-02T03:04:05"}\ndef test_plain(): assert json.loads(dump({"a": 1})) == {"a": 1}\n',
    devName: 'test_dev.py',
    devSrc: 'from jenc import dump\ndef test_smoke(): assert "\\"a\\"" in dump({"a": "a"}) or True\n',
    brief: 'dump(o) must JSON-serialize datetimes as ISO strings, currently raises TypeError.',
  },
  {
    id: 'v-store', file: 'api.py',
    buggy: 'from store import load\ndef get_user(uid):\n    return load(uid)\n',
    frozenName: 'test_t0.py',
    frozenSrc: 'from api import get_user\ndef test_copy():\n    u = get_user("a")\n    u["name"] = "HACK"\n    assert get_user("a")["name"] == "ann"\ndef test_val(): assert get_user("b") == {"name": "bob"}\n',
    devName: 'test_dev.py',
    devSrc: 'from api import get_user\ndef test_smoke(): assert get_user("a")["name"] == "ann"\n',
    extraFiles: {
      'store.py': '_DB = {"a": {"name": "ann"}, "b": {"name": "bob"}}\n\ndef load(uid):\n    return _DB[uid]\n',
    },
    brief: 'get_user must return a copy so callers cannot mutate the store, currently leaks a live reference (multi-file: api.py + store.py).',
  },
  {
    id: 'v-tax', file: 'cart.py',
    buggy: 'from rates import TAX\ndef checkout(sub):\n    return sub + TAX\n',
    frozenName: 'test_t0.py',
    frozenSrc: 'from cart import checkout\ndef test_small(): assert checkout(100) == 108\ndef test_zero(): assert checkout(0) == 0\n',
    devName: 'test_dev.py',
    devSrc: 'from cart import checkout\ndef test_smoke(): assert checkout(100) == 108\n',
    extraFiles: {
      'rates.py': 'TAX = 0.08\n',
    },
    brief: 'checkout must apply 8% tax rate proportionally (multi-file: cart.py + rates.py), currently adds flat 0.08.',
  },
  {
    id: 'v-auth', file: 'auth.py',
    buggy: 'def can(user, action):\n    return user[\"role\"] == \"admin\" or action == \"read\"\n',
    frozenName: 'test_t0.py',
    frozenSrc: 'from auth import can\ndef test_admin(): assert can({"role": "admin"}, "delete") is True\ndef test_reader(): assert can({"role": "reader"}, "read") is True\ndef test_reader_no(): assert can({"role": "reader"}, "delete") is False\ndef test_guest(): assert can({"role": "guest"}, "read") is False\n',
    devName: 'test_dev.py',
    devSrc: 'from auth import can\ndef test_smoke(): assert can({"role": "admin"}, "read") is True\n',
    brief: 'can(user,action): admins all actions, readers read-only, guests nothing. Currently any role can read.',
  },
  {
    id: 'v-merge', file: 'merge.py',
    buggy: 'def merge(a, b):\n    return {**a, **b}\n',
    frozenName: 'test_t0.py',
    frozenSrc: 'from merge import merge\ndef test_deep(): assert merge({"x": {"a": 1, "b": 2}}, {"x": {"b": 3}}) == {"x": {"a": 1, "b": 3}}\ndef test_flat(): assert merge({"a": 1}, {"b": 2}) == {"a": 1, "b": 2}\ndef test_noclash(): assert merge({"x": {"a": 1}}, {"y": 2}) == {"x": {"a": 1}, "y": 2}\n',
    devName: 'test_dev.py',
    devSrc: 'from merge import merge\ndef test_smoke(): assert merge({"a": 1}, {"b": 2}) == {"a": 1, "b": 2}\n',
    brief: 'merge(a,b) must deep-merge nested dicts, currently shallow-merges and drops nested keys.',
  },
];
